config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"

  devise_for :admin_users
  devise_for :associates, controllers: { registrations: "associates/registrations", sessions: "associates/sessions" }

  resources :companies do
    resources :associates
    resources :properties
    resources :general_meetings
    resources :financial_operations
    resources :tenants
  end

  authenticate :admin_user do
    namespace :admin do
      root "dashboard#index"

      resources :admin_users

      resources :companies do
        resources :associates
        resources :properties
        resources :general_meetings
        resources :financial_operations
        resources :tenants
      end
      resources :associates, only: [ :index ]
    end
  end
end

app/views/shared/_admin_navbar.html.erb
<% if current_admin_user %>
  <nav id="admin-navbar" class="navbar navbar-expand-md navbar-light">
    <button class="navbar-toggler" data-target="#admin-navbar-collapse" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="admin-navbar-collapse" class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to admin_root_path, class: 'nav-link' do %>
            <i class="fas fa-eye"></i>
            <b>Admin' - SCI-Facile</b>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_admin_user_path(current_admin_user), class: 'nav-link' do %>
            <i class="fas fa-user"></i>
            <%= current_admin_user.email %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/shared/_company_navbar.html.erb
<nav id="company-navbar" class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow">
  <div class="container">
    <span class="navbar-brand fw-bold text-primary">
      <%= link_to root_path, class: "text-decoration-none" do %>
        SCI-Facile <i class="fas fa-building"></i>
      <% end %>
      <%= link_to @company.name, company_path(@company), class: "text-decoration-none" %>
    </span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to company_associates_path(@company), class: "nav-link" do %>
            <i class="fas fa-user-group text-primary"></i>
            <%= t("activerecord.models.associate.other") %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to company_properties_path(@company), class: "nav-link" do %>
            <i class="fas fa-building text-primary"></i>
            <%= t("activerecord.models.property.other") %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to company_financial_operations_path(@company), class: "nav-link" do %>
            <i class="fas fa-file-invoice-dollar text-primary"></i>
            <%= t("activerecord.models.financial_operation.other") %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to company_tenants_path(@company), class: "nav-link" do %>
            <i class="fas fa-home-user text-primary"></i>
            <%= t("activerecord.models.tenant.other") %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to company_general_meetings_path(@company), class: "nav-link" do %>
            <i class="fas fa-pen text-primary"></i>
            <%= t("activerecord.models.general_meeting.other") %>
          <% end %>
        </li>
        <% if associate_signed_in? %>
          <li class="nav-item ms-2">
            <%= link_to current_associate.email, company_associate_path(current_associate.company, current_associate), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_associate_session_path, data: { turbo_method: "delete" }, class: "nav-link", title: "Déconnexion" do %>
              <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item ms-2">
            <%= link_to "Connexion", new_session_path(:associate), class: "btn btn-outline-primary rounded-pill" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice.html_safe %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert.html_safe %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow">
  <div class="container">
    <a class="navbar-brand fw-bold" href="#">SCI-Facile <i class="fas fa-building me-2"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/#fonctionnalites">Fonctionnalités</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/#tarif">Tarif</a>
        </li>
        <% if associate_signed_in? %>
          <li class="nav-item ms-2">
            <%= link_to current_associate.email, company_associate_path(current_associate.company, current_associate), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_associate_session_path, data: { turbo_method: "delete" }, class: "nav-link", title: "Déconnexion" do %>
              <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item ms-2">
            <%= link_to "Connexion", new_session_path(:associate), class: "btn btn-outline-primary rounded-pill" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>